### PR TITLE
Updates to Pro upgrade info within settings

### LINKED ISSUE #76: Updates to Pro upgrade info within settings for 2.1.0
Make current to reflect latest Pro version.

Update info in sidebar and payment form settings.

### PR DESCRIPTION
**Pull request by pderksen**
Closes #76

### CODE REVIEW

**Comment by pderksen** [comment]
Missed one thing. More commits incoming.

**Comment by spencerfinnell** [comment]
Perhaps "Custom Form Builder" or "Unlimited Custom Fields" instead of just "Custom Fields"?

**Comment by pderksen** [comment]
@spencerfinnell Ready to review and merge now. Changed the payment form settings upgrade area to include a bulleted list to match the sidebar upgrade area.

**Comment by spencerfinnell** [comment]
Super small nitpick, but putting a `<br />` before `WP Simple Pay Pro` makes the full name stand out more/easier to read.

https://cloudup.com/cAH7xqDnVJi

**Comment by pderksen** [comment]
Agreed. I think it naturally had the break there before I widened the sidebar.

**Pull request merged**
